### ISSUE TITLE
Script running but not giving the flag

### ISSUE THREAD

**Issue by Aviral2642** [vflame6/ringzer0ctf-challenges#1]
what exactly i have to do ??
i copied the file saved it on my dektop with .py extension and run it with python3 file.py
it ran but no output ???

what should i do

**Comment by vflame6** [comment]
Hello, I think you shouldn't just copy the file and wait a flag from it. Please try to solve the challenge by yourself first.
Which file are you talking about?

**Comment by vflame6** [comment]
Hello, @Aviral2642!
I think you shouldn't just copy the file and wait a flag from it. Please try to solve the challenge by yourself first.
Which file are you talking about?

**Comment by vflame6** [comment]
Are you there, @Aviral2642 ?
